// pages/api/promotions.js
import { getDatabasePool } from '../classes/Database'; 
import multer from 'multer';

// Configure multer to store files in the 'public/images' directory
const upload = multer({ dest: 'public/images' });

export default async function handler(req, res) {
    upload.single('image')(req, {}, async (err) => {
        if (err) {
            res.status(500).json({ error: err.message });
            return;
        }

        if (req.method === 'POST') {
            const { title, subtitle, is_active } = req.body;
            const image = req.file;

            const errors = [];
            if (!title) errors.push('Title is empty!');
            if (!subtitle) errors.push('Subtitle is empty!');
            if (!image) errors.push('Image is empty or type is not supported!');

            if (errors.length > 0) {
                res.status(400).json({ errors });
                return;
            }

            const data = {
                title,
                subtitle,
                is_active,
                image: image.filename, // Use the filename generated by multer
            };

            const result = await create('promotions', data);

            if (result) {
                res.status(200).json({ status: 'success' });
            } else {
                res.status(500).json({ error: 'Something went wrong!' });
            }
        } else {
            res.status(405).json({ error: 'Method not allowed' });
        }
    });
}